baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Terminal Blog"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "TIL"
    url = "/til/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
